### ISSUE TITLE
Introductory doc notes

### ISSUE THREAD

**Issue by pdiakumis** [PMCC-BioinformaticsCore/janis#1]
This is great work folks, just started playing with the examples. Understand that it's still in heavy dev, but I took a couple of notes going through the intro doc which might help other noobs getting started. Can submit a PR if you want.

- Py3 `pip` is needed for installation; couldn't get it to work with my default, rusty Py2 `pip`:

```
$ pip install janis-pipelines
Collecting janis-pipelines
  Could not find a version that satisfies the requirement janis-pipelines (from versions: )
No matching distribution found for janis-pipelines
$ pip --version
pip 18.0 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
```

- Not sure what the brackets are here for:

```
pip install janis-pipelines[bioinformatics] # this works fine: pip install janis-pipelines.bioinformatics
```

- `dump_translation` was changed to `translate` in 73adb94789ef121a8469e9fa77bb154ad142cb36 - first example needs an update:

```
w.dump_translation("cwl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Workflow' object has no attribute 'dump_translation'
```

Cheers - Peter

**Comment by illusional** [comment]
Thanks Peter! Appreciate the feedback. 

I've caught the rest of the `dump_translation`, and replaced pip with pip3 (edf565e2fe5a15faad7c833a81fd5de88b4da169) - I generally replace my Python with conda, and forget that's not the norm.

We've separated the bioinformatics tools definitions from the main workflow building classes into separate repositories; by including the `[bioinformatics]` _extra_ when you install, ie: `pip3 install janis-pipelines[bioinformatics]`, you also install the [bioinformatics tools](https://pypi.org/project/janis-pipelines.bioinformatics/).

https://github.com/PMCC-BioinformaticsCore/janis/blob/edf565e2fe5a15faad7c833a81fd5de88b4da169/setup.py#L34-L36

**Comment by pdiakumis** [comment]
Ha, for the zsh shell you need to quote the last bit, or else it doesn't recognise it:

```
(janis) ➜  ~ pip install janis-pipelines[bioinformatics]
zsh: no matches found: janis-pipelines[bioinformatics]

(janis) ➜  ~ pip install "janis-pipelines[bioinformatics]"
Collecting janis-pipelines[bioinformatics]
  Using cached https://files.pythonhosted.org/packages/eb/6e/ae04f5e2c95b522bb8aa39f3f80d34035ad67e3abf09d0cab2286ba740c7/janis_pipelines-0.2.16-py3-none-any.whl
Collecting illusional.wdlgen (from janis-pipelines[bioinformatics])
[...]
```

Thanks!
