### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by tirohia** [PMCC-BioinformaticsCore/janis#14]
Hi - I am assuming this is a documentation thing - the documentation appears to be around version 0.8, I'm currently running 0.9 and what with being a work in progress, I'm assuming a documentation/version mismatch. If it's not though ...

tldr; the test examples provided to make sure everything works fine, don't work for me. 

Using janis v9.*  using python 3.6.9

```
(env) bcurran@pequod:/blue/project/dev/src$ janis -v
--------------------  ------
janis-core            v0.9.6
janis-assistant       v0.9.8
janis-bioinformatics  v0.9.4
janis-templates       v0.9.1
janis-unix            v0.9.0
janis-pipelines       v0.9.1
--------------------  ------
```

The install of Janis appears to work fine, no errors are thrown during the install of janis-pipelines or cwltool. 
Running the test line from the documentation:
`janis run --engine cwltool --stay-connected hello`
results in error: unrecognized arguments: --stay-connected

I'm assuming that the --stay-connected option is just something that has been removed at some point as I can't see it in the help. Removing it however, does not help, 

```
(env) bcurran@pequod:/blue/project/dev/src$ janis run --engine cwltool hello
Traceback (most recent call last):
  File "/home/bcurran/janis/env/bin/janis", line 8, in <module>
    sys.exit(process_args())
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/cli.py", line 140, in process_args
    return cmds[args.command](args)
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/cli.py", line 675, in do_run
    no_store=args.no_store,
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/main.py", line 395, in fromjanis
    row = cm.create_task_base(wf, outdir=output_dir, store_in_centraldb=not no_store)
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/management/configmanager.py", line 100, in create_task_base
    f"You must specify an output directory (or specify an '{JanisConfiguration.Keys.OutputDir.value}' "
Exception: You must specify an output directory (or specify an 'output_dir' in your configuration)

```
If I then specify an output directory (I think I've got the flags right), it in turn doesn't recognize the inputs ...

```
(env) bcurran@pequod:/blue/project/dev/src$ janis run --engine cwltool hello --output-dir "/blue/project/dev/src"
Traceback (most recent call last):
  File "/home/bcurran/janis/env/bin/janis", line 8, in <module>
    sys.exit(process_args())
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/cli.py", line 140, in process_args
    return cmds[args.command](args)
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/cli.py", line 675, in do_run
    no_store=args.no_store,
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/main.py", line 391, in fromjanis
    batchrun_options=batchrun_reqs,
  File "/home/bcurran/janis/env/lib/python3.6/site-packages/janis_assistant/utils/inputshelper.py", line 35, in cascade_inputs
    f"There were unrecognised inputs provided to the tool \"{wf.id()}\", keys: {', '.join(invalid_keys)}"
Exception: There were unrecognised inputs provided to the tool "hello", keys: output_dir
```
I wouldn't be worried as much if I was then not having problems with the example code Building a worklfow (tutorial 1) of the documentation. 

Cheers
Ben.

**Comment by illusional** [comment]
Hey Ben, thanks for checking out the project and raising an issue. I think you’re right, we don’t document this well (especially with a slight change in behaviour in v0.9.x).

You’ve got the flag correct, but Python is a little picky with where it goes (it needs to go before the workflow name):

```
janis run --engine cwltool --output-dir "/blue/project/dev/src" hello
```

All inputs after the workflow name become inputs to the workflow:

```
janis run [workflowoptions] -o outputdir hello —inp “this string is passed as an input to the workflow”
```

**Comment by illusional** [comment]
Sorry, I've missed a bit of your comment too. There was a change in behaviour from v0.8.x to v0.9.x about how Janis runs (ie: foreground or background), and there's a bit more interaction from a template you use.

In 0.8.x, Janis would run in the background and it was confusing whether Janis would stop running. 

In 0.9.x by default, Janis will run Cromwell (and cwltool) in the foreground. This can be changed by using the `-B` (`--background`) flag (sort of equivalent to running `nohup janis [options] &`). On some templates, running in the background is the default. Janis will usually run on the head node, but could also be configured to submit itself as a job to Slurm.

Takeaways:

- `--stay-connected` has been removed and running in the foreground is now the default
- Janis be run in the background with `--background` or `-B`

### Workshops:

> I've written updated workshops that will get migrated into the docs soon, but they are more up to date:
> 
> - [Workshop 1](https://github.com/PMCC-BioinformaticsCore/janis-workshops/tree/master/workshop1)
> - [Workshop 2](https://github.com/PMCC-BioinformaticsCore/janis-workshops/tree/master/workshop2)

**Comment by illusional** [comment]
Hey @tirohia, thanks again for raising this issue. I've updated the tutorials to reflect the changes in the Janis CLI, and now also includes sample data (for Tutorial 1 and 2).
