### ISSUE TITLE
omit docker runtime when container is none

### ISSUE THREAD

**Issue by matthdsm** [PMCC-BioinformaticsCore/janis#15]
When the container definition is empty or `None`, the container is added as "None".
Could the container definition be omitted on translation instead?
Thanks
M

**Comment by illusional** [comment]
I'm a little concerned that this will hurt the portability of tools, but I think it's something you should be able to do. I think we'll restrict all tools in the registry to have containers, but I'm less concerned for tools in your own registry.

I don't have good documentation for it, but you can create your own registry (to interact with Janis) by following the structure of janis-bioinformatics, and then in `setup.py` for the pip module and then include the following entry points:

```
entry_points={
    "janis.extension": ["yourregistry=your_registry"],
    "janis.tools": ["yourregistry= your_registry.tools"],
    "janis.types": ["yourregistry= your_registry.data_types"],
},
```

Let me know if you do this, and feel free to ping me if you have any trouble. I'll fix the containers being set to the string "None".

**Comment by matthdsm** [comment]
I'm having issues with bcl2fastq wrt to this. 
We do have a usable docker image, but we can't open source it due to the licensing from Illumina.
I you want to restrict the registry to tools with a docker image, I'm going to have to close the bcl2fq PR. That would be a pity though, since the tool is very widely used.

M

**Comment by matthdsm** [comment]
Perhaps there's a way to throw a warning pointing out that users have to add their own image to the tool definition?

**Comment by illusional** [comment]
Hmm, this is a little more complex than I first thought, I'll have a think and get back to you.

**Comment by illusional** [comment]
Hey @matthdsm, this has been implemented. It's not documented or released yet, but you will be able to have empty container by passing `--allow-empty-container` to `janis run / translate`. If you're translating within the API, all classes now have `tool.translate("language", allow_empty_container=True/False)`.

You'll need updates to janis_core (v0.9.8) and janis_assistant (v0.9.10), which have now been released.

**Comment by matthdsm** [comment]
Awesome! Thanks a lot!

M
