### ISSUE TITLE
janis query suggests using 'janis cleanup' to clean up your tasks, but cleanup is not accepted as an argument

### ISSUE THREAD

**Issue by bjpop** [PMCC-BioinformaticsCore/janis#22]
I ran `janis query`

It said [WARN]: Couldn't get information for tasks: cdad71, run'janis cleanup' to clean up your tasks.

I tried:

$ janis cleanup

Got this error:

error: argument command: invalid choice: 'cleanup' (choose from 'run', 'init', 'translate', 'inputs', 'watch', 'resume', 'pause', 'abort', 'rm', 'metadata', 'spider', 'query', 'version', 'docs')

**Comment by illusional** [comment]
Thanks for the report @bjpop, I've implemented this in the linked branch, it is due to be released soon.

**Comment by illusional** [comment]
Released in janis-assistant [`v0.9.13`](https://github.com/PMCC-BioinformaticsCore/janis-assistant/releases/tag/v0.9.13).
