### ISSUE TITLE
janis query critical error: [CRITICAL]: Couldn't check workflow 'cdad71': No module named 'janis_assistant.data.models.filescheme'

### ISSUE THREAD

**Issue by bjpop** [PMCC-BioinformaticsCore/janis#23]
When I run `janis query` I get the following message:

`[CRITICAL]: Couldn't check workflow 'cdad71': No module named 'janis_assistant.data.models.filescheme'`

I can still use the `janis query` to do what I want. Reporting here just in case.

**Comment by illusional** [comment]
This is related to me moving the location of Filescheme to be better oganised, how SQLiteDict and hence Pickle relies on the path to deserialise.

I've added back an import for Pickle to find this class for older workflows (`< v0.9.11`) in https://github.com/PMCC-BioinformaticsCore/janis-assistant/commit/7942ad06add2a5c7c6bc05b377a86c3ff17c7629. I intend to release this fix soon, just waiting on an unrelated issue.

**Comment by illusional** [comment]
This was resolved in: https://github.com/PMCC-BioinformaticsCore/janis-assistant/commit/7942ad06add2a5c7c6bc05b377a86c3ff17c7629
