### ISSUE TITLE
 Error parsing generated wdl using pbs_singularity

### ISSUE THREAD

**Issue by lonsbio** [PMCC-BioinformaticsCore/janis#29]
Janis installed with `pbs_singularity` gives an error running `hello` workflow: 

`janis run -o tutuorial0 hello`

which hangs, and the log ends with a ` ERROR - Error parsing generated wdl` contaning:

```
...
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: wdl.draft2.parser.WdlParser$SyntaxError: Unrecognized token on line 25, column 83:
    walltime='00:00:~{duration}' # $(echo $((${runtime_minutes} * 60)) | dc -e '?1~r60~r60~r[[0]P]szn[:]ndZ2>zn[:]ndZ2>zn')
...
```

**Comment by illusional** [comment]
Thanks for the issue @lonsbio. For context, this is related to configuring Cromwell to submit to a PBS cluster - essentially our configuration wasn't correct.

I've pushed a set of changes to janis-assistant (https://github.com/PMCC-BioinformaticsCore/janis-assistant/commit/15f1b425076e676aed9673b1237f536269886e32) to address this, and bump up the quality of the qsub definitions. I don't have access to a pbs cluster so it's harder for me to test this, but I'd be keen to work with you to get this functional again.

You can get these changes by updating janis-core (0.10.5) / janis-assistant (0.10.4) to the latest (as of 6:29pm AEST today) release -- updating the assistant will automatically update core.

```bash
pip3 install --upgrade --no-cache 'janis-pipelines.runner >= 0.10.4'
```

The new definitions parse the Cromwell validation and by inspection they look okay. This is what the generated sbatch script would now look like (where <output-dir> and <container-dir> are inserted by Janis for you):

```bash
chmod +x <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/script
docker_subbed=$(sed -e 's/[^A-Za-z0-9._-]/_/g' <<< ubuntu@sha256:5747316366b8cc9e3021cd7286f42b2d6d81e3d743e2ab571f55bcd5df788cc8)
image=<container-dir>/$docker_subbed.sif
jobname=hello-cpu-1-mem-4096
walltime='00:00:86400'
if [ ! -f $image ]; then
   singularity pull $image docker://ubuntu@sha256:5747316366b8cc9e3021cd7286f42b2d6d81e3d743e2ab571f55bcd5df788cc8
fi
JOBID=$(echo \
   " \
   singularity exec --bind <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello:/cromwell-executions/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello $image /bin/sh /cromwell-executions/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/script" \
qsub \
     -v <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello \
     -N $jobname \
      \
      \
     -o <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/stdout \
     -e <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/stderr \
     -l nodes=1:ppn=1,mem=4096mb,walltime=$walltime | cut -d. -f1 )  \
&& NTOKDEP=$(echo '[ ! -f rc ] && (echo 1 >> <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/rc) && (echo "A slurm error occurred" >> <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/stderr)' | qsub -m p -W depend=afternotok:$JOBID -l nodes=1:ppn=1,mem=1GB,walltime=00:01:00) \
&& echo $JOBID
```

**Comment by lonsbio** [comment]
Thanks so much @illusional 

Progress made! Now the issue occurs at the PBS script, which I can appreciate is hard to debug without a PBS cluster! The first `qsub` call seems to be missing the  leading pipe `|` in your example above and  on my end when I run the tutorial, even though it looks like it should be there from the source code. For example, in the above:

```
  singularity exec --bind <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello:/cromwell-executions/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello $image /bin/sh /cromwell-executions/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/script" \
qsub \
```

should be 

```
  singularity exec --bind <output-dir>/janis/execution/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello:/cromwell-executions/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello $image /bin/sh /cromwell-executions/hello/b9779329-5a58-4753-ac86-554aa9534fd6/call-hello/execution/script" \
| qsub \
```

but from `cromwellconfiguration.py` I can't figure out why it is missing. Manually adding the pipe to the `/execution/script.submit ` seems to fix it so I think it's close

**Comment by illusional** [comment]
Ahh, good catch. I can see it get's passed to the cromwell config, but it gets lost somewhere in the command creation I guess. I've moved it to the end of the previous line in https://github.com/PMCC-BioinformaticsCore/janis-assistant/commit/c22a934c494b7ffa7fdbba31bf0ef20e7263fa32, here's how to install from github:

```bash
pip3 install --no-dependencies --upgrade git+https://github.com/PMCC-BioinformaticsCore/janis-assistant.git
```

**Comment by lonsbio** [comment]
That does the trick, `Hello, world!` achievement unlocked. Thanks for fixing so quickly!
