### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by matthdsm** [PMCC-BioinformaticsCore/janis#7]
Hi,

I've been looking around for a library exactly like this one. We're looking into migrating all our pipelines to CWL/WDL so this project could be gold to us.

Soooo, any chance on a stable release any time soon? I'd like to make sure janis is here to stay before putting my eggs in the proverbial basket.

Cheers
M

**Comment by illusional** [comment]
Hey @matthdsm, thanks for taking the time to look through the project and already contributing more tools!

We're pretty confident that the current API structure is not going to change in a major way between new versions. In the interest of transparency, I've added issues for our next major features planned:

- Expressions (#8)
- Union types (#10)
- Time / Disk requirements (#11)
- Conditionals (#9)

These are all features being **added** to the language, and we're expecting that they will all be backwards compatible with previous workflows. I've added a few comments to these issues about why we believe they will be backwards compatible. 

I'll acknowledge that our documentation about the API and how to use Janis is quite lacking, and it's something that is a priority for us. 

In the meantime, here are two workshops:
- [Workshop 1](https://github.com/PMCC-BioinformaticsCore/janis-workshops/blob/master/workshop1/) - Introduction to Janis, how to run basic workflows, etc.
- [Workshop 2](https://github.com/PMCC-BioinformaticsCore/janis-workshops/blob/master/workshop2) - How to build an alignment workflow, wrap a new tools, registry and a little bit more.

I'd love your feedback on the API, documentation or anything else to help us be a scientist-friendly framwork.

**Comment by matthdsm** [comment]
Hi Michael,

Thanks for the detailed info. I think I've already got the hang of the API, which says a lot about the framework (awesome!).
I'm looking forward to the additions planned, fits right up my alley. I hope be able to keep adding tools as I need them (as far as they aren't already available)

Cheers
M
